language: node_js
node_js:
    - "8"
before_install:
    - "npm install --save-dev nyc"
    - "npm install --save-dev source-map-support"
after_success:
    - "npm run coverage"
cache:
  directories:
    - "node_modules"
